<div class="row">
<div class="col-sm-8"><h2>Editar cuenta</h2></div>
<div class="col-sm-4">
	<a href="<?php echo APP_URL.'transacciones'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="glyphicon glyphicon-plus"></span> Lista de transacciones
		</button>
	</a>
	<a href="<?php echo APP_URL.'categorias'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="glyphicon glyphicon-plus"></span> Lista de categorias
		</button>
	</a>
	<a href="<?php echo APP_URL.'usuarios'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="glyphicon glyphicon-plus"></span> Lista de cuentas
		</button>
	</a>
</div>				
</div>
</div>
<div class="container">
	<div class="col-md-6 mx-auto">		
		<form action="<?php echo APP_URL."usuarios/editar"; ?>" method="POST">
			<input type="hidden" name="id" value="<?php echo $this->usuario["id"]; ?>">
			<div class="form-group">
				<label for="nombre">Nombre</label>
				<input type="text" name="nombre" class="form-control" value="<?php echo $this->usuario["nombre"]; ?>">
			</div>
			<button type="submit" class="btn btn-primary"><span class="fa fa-check"></span> Guardar</button>
		</form>
	</div>
</div>
