<div class="row">
<div class="col-sm-8" ><h2>Lista de cuentas</h2></div>
<div class="col-sm-4">
	<a href="<?php echo APP_URL.'transacciones'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="glyphicon glyphicon-plus"></span> Lista de transacciones
		</button>
	</a>
	<a href="<?php echo APP_URL.'categorias'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="glyphicon glyphicon-plus"></span> Lista de categorias
		</button>
	</a>
	<a href="<?php echo APP_URL.'usuarios/agregar'; ?>">
		<button class="btn btn-sm btn-primary">
			<span class="fa fa-plus"></span> Cuenta
		</button>
	</a>
</div>		
</div>
	</div>
	<div class="table-responsive">
	<table class="table">
		<tr>
			<th>ID</th>
			<th>Nombre</th>
			<th>Accion</th>
		</tr>
		<tr>
			<?php foreach ($this->usuarios as $usuario): ?>
				<tr>
					<td><?php  echo $usuario["id"];?></td>
					<td><?php  echo $usuario["nombre"];?></td>
					<td>
						<a href="<?php  echo APP_URL.'usuarios/editar/'.$usuario["id"]; ?>">
							<button class="btn btn-sm btn-primary">
								<span class="fa fa-paint-brush"></span> Editar
							</button>
						</a>
						<a href="<?php  echo APP_URL.'usuarios/Eliminar/'.$usuario["id"]; ?>">
							<button class="btn btn-sm btn-primary">
								<span class="fa fa-trash"></span> Eliminar
							</button>
						</a>
					</td>
				</tr>
			<?php endforeach ?>
		</tr>
	</table>
    </div>